ad:
  user:
  password:
  server:
  treebase:
collection_registry_url: https://medusa.library.illinois.edu
db_host:                 postgres
db_port:                 5432
db_database:             metaslurp
db_username:             postgres
db_password:             postgres
dls_url:                 https://digital.library.illinois.edu
opensearch_endpoint:     http://opensearch:9200
opensearch_index:        metaslurp
image_server_endpoint:   http://cantaloupe:8182
image_server_username:
image_server_secret:
max_items_to_harvest:    5000
mail:
  from: "noreply@example.edu"
  reply_to: "metaslurp@example.edu"
  smtp:
    address:
    port:
    user_name:
    password:
    authentication: plain
    enable_starttls_auto: true
saml:
  sp_entity_id:            "https://localhost:3000/saml"
  sp_private_key:
  idp_sso_service_url:     "https://shibboleth.illinois.edu/idp/profile/SAML2/Redirect/SSO"
  idp_sso_service_binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
admin_emails:            admin@example.org
medusa_admins_group:     Library Medusa Admins
root_url:                http://localhost:3000
secret_key_base:         whateverdoesntmatter
# This is used in tests
test:
  key: value